### ISSUE TITLE
Why does it not use strapi relationships?

### ISSUE THREAD

**Issue by jaschaio** [VirtusLab-Open-Source/strapi-plugin-comments#130]
I don't understand enough about the plugin yet and I am fairly new to Strapi, but it seems odd to me that this plugin is not using the build in strapi relationship types to relate comments to posts for example.

Any particular reason for that architectural decision? It breaks a lot of default strapi features and replaces them with a rather odd api, e.G. `/api/comments/api::post.post:400`

**Comment by cyp3rius** [comment]
Hello @jaschaio ,

Such decision was based on our experience with Strapi v3 and Polymorphic relations which were part of it. Since beginning Comments plugin in `v1.x` was based on such relations but the support was really low and keeping them got couple effects:
- poly relation was working differently on different DBs, so complexity
- there was no possibility to setup such relation for your models via Content Type Builder and once such relation was part of model, builder crashes

I think those two points explains enough ;) In simple words, while reworking plugin for Strapi v4 we took the lessons and recent `v1.0` changes (including decommissioning poly) to make this plugin as flexible as it can be. If such advanced relations like poly but with better support are going to be introduced to the core, I think we might consider them. But because each built-in relation required separated related field it's not possible to maintain it.

In addition, the API you're referring to hasn't changed since beginning and we're supporting it also here. Because it's a plugin with a lot of custom stuff you can't expect it to be CRUD like.

**Comment by cyp3rius** [comment]
Duplicated of #127

**Comment by jaschaio** [comment]
Thanks for explaining
